### ISSUE TITLE
Webhook fails after new order in 1.5.6

### ISSUE THREAD

**Issue by cjohansson** [Nets-eCom/Magento2_easy#38]
We get an error when placing new order

Magento 2.4.4
PHP: 8.1
Dibs_Easycheckout: 1.5.6

**Comment by cjohansson** [comment]
Placing an order creates this error and I think this is preventing order e-mails from being sent

```
[2022-09-01T13:58:17.930131+00:00] main.CRITICAL: Error: Call to undefined method Dibs\EasyCheckout\Logger\Logger::addInfo() in /var/www/html/app/code/Dibs/EasyCheckout/Controller/Webhook/Webhook.php:293
Stack trace:
#0 /var/www/html/app/code/Dibs/EasyCheckout/Controller/Webhook/Webhook.php(140): Dibs\EasyCheckout\Controller\Webhook\Webhook->logInfo('Process - Valid...')
#1 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Dibs\EasyCheckout\Controller\Webhook\Webhook->execute()
#2 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Dibs\EasyCheckout\Controller\Webhook\CheckoutCompleted\Interceptor->___callParent('execute', Array)
#3 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Dibs\EasyCheckout\Controller\Webhook\CheckoutCompleted\Interceptor->Magento\Framework\Interception\{closure}()
#4 /var/www/html/generated/code/Dibs/EasyCheckout/Controller/Webhook/CheckoutCompleted/Interceptor.php(23): Dibs\EasyCheckout\Controller\Webhook\CheckoutCompleted\Interceptor->___callPlugins('execute', Array, Array)
#5 /var/www/html/vendor/magento/framework/App/FrontController.php(248): Dibs\EasyCheckout\Controller\Webhook\CheckoutCompleted\Interceptor->execute()
#6 /var/www/html/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse(Object(Dibs\EasyCheckout\Controller\Webhook\CheckoutCompleted\Interceptor), Object(Magento\Framework\App\Request\Http))
#7 /var/www/html/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest(Object(Magento\Framework\App\Request\Http), Object(Dibs\EasyCheckout\Controller\Webhook\CheckoutCompleted\Interceptor))
#8 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#9 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#10 /var/www/html/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(99): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#11 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#12 /var/www/html/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(75): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#13 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#14 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#15 /var/www/html/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#16 /var/www/html/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#17 /var/www/html/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#18 /var/www/html/pub/index.php(30): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#19 {main} [] []
```

**Comment by sldabhi** [comment]
Hi Christian,

This issue related to webhook has been resolved. Kindly check with latest version released 1.5.7.
Thank you

**Comment by sursi** [comment]
Hi,

Can you please confirm if still facing same issue with version 1.5.7?

**Comment by kbhansen** [comment]
Hi
This still happens in 1.5.7
It's not resolved.

**Comment by kbhansen** [comment]
I implemented the fix from 
https://github.com/cjohansson/Magento2_easy/commit/0aea54c1eb5caac36734a64397a1ff928ff140b1

...and can confirm that it works.

**Comment by sursi** [comment]
Hi @kbhansen, thank you for the confirmation.

We will merge this in next release and closing this issue.
